// Generated by CoffeeScript 1.9.3
(function() {
  jQuery(function() {
    return jQuery('form.ajax-action').each(function(i, f) {
      var $form, $result, a, resultContainerSel;
      $form = $(f);
      a = Action.form($form, {
        clear: $form.data('clear') || false,
        fadeOut: $form.data('fadeout') || false,
        onSuccess: function(resp) {
          var cb;
          cb = eval($form.data('onsuccess'));
          if (cb) {
            return cb.call(resp);
          }
        }
      });
      resultContainerSel = $form.data('result-container');
      $result = void 0;
      if (resultContainerSel) {
        $result = $(resultContainerSel);
      } else {
        $result = $form.find(".action-result-container");
      }
      if (!$result.get(0)) {
        $result = $form.parent().find(".action-result-container");
      }
      if (!$result.get(0)) {
        $result = $("<div/>").addClass("action-result-container");
        $form.before($result);
      }
      return a.plug(ActionMsgbox, {
        container: $result,
        scrollOffset: $form.data('scroll-offset'),
        fadeOut: false
      });
    });
  });

}).call(this);
